//types
export const GET_DATA = "GET DATA";
export const CLICK = "CLICK";
export const TRAILER = "TRAILER";
export const COLOR = "COLOR";
export const VIDEOS = "VIDEOS";
export const IMAGES = "IMAGES";
//signup
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
//login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
//get watchlist
export const GET_WATCHLIST_REQUEST = "GET_WATCHLIST_REQUEST";
export const GET_WATCHLIST_SUCCESS = "GET_WATCHLIST_SUCCESS";
export const GET_WATCHLIST_FAILURE = "GET_WATCHLIST_FAILURE";
//add watchlist
export const ADD_TO_WATCHLIST_REQUEST = "ADD_TO_WATCHLIST_REQUEST";
export const ADD_TO_WATCHLIST_SUCCESS = "ADD_TO_WATCHLIST_SUCCESS";
export const ADD_TO_WATCHLIST_FAILURE = "ADD_TO_WATCHLIST_FAILURE";
//remove watchlist
export const REMOVE_FROM_WATCHLIST_REQUEST = "REMOVE_FROM_WATCHLIST_REQUEST";
export const REMOVE_FROM_WATCHLIST_SUCCESS = "REMOVE_FROM_WATCHLIST_SUCCESS";
export const REMOVE_FROM_WATCHLIST_FAILURE = "REMOVE_FROM_WATCHLIST_FAILURE";
//get favorite
export const GET_FAVORITE_REQUEST = "GET_FAVORITE_REQUEST";
export const GET_FAVORITE_SUCCESS = "GET_FAVORITE_SUCCESS";
export const GET_FAVORITE_FAILURE = "GET_FAVORITE_FAILURE";
//add favorite
export const ADD_TO_FAVORITE_REQUEST = "ADD_TO_FAVORITE_REQUEST";
export const ADD_TO_FAVORITE_SUCCESS = "ADD_TO_FAVORITE_SUCCESS";
export const ADD_TO_FAVORITE_FAILURE = "ADD_TO_FAVORITE_FAILURE";
//remove favorite
export const REMOVE_FROM_FAVORITE_REQUEST = "REMOVE_FROM_FAVORITE_REQUEST";
export const REMOVE_FROM_FAVORITE_SUCCESS = "REMOVE_FROM_FAVORITE_SUCCESS";
export const REMOVE_FROM_FAVORITE_FAILURE = "REMOVE_FROM_FAVORITE_FAILURE";
//CHANGEPASSWORD
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";
//CHANGEPROFILE
export const CHANGE_PROFILE_REQUEST = "CHANGE_PROFILE_REQUEST";
export const CHANGE_PROFILE_SUCCESS = "CHANGE_PROFILE_SUCCESS";
export const CHANGE_PROFILE_FAILURE = "CHANGE_PROFILE_FAILURE";
